# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.
# Do not edit this file directly.

from __future__ import annotations

from src.graph._generated.models import (
    Behind,
    Bus,
    Car,
    Cyclist,
    EgoVehicle,
    InFrontOf,
    InLane,
    Lane,
    LeftAdjacentTo,
    LeftOf,
    Motorcycle,
    Overlaps,
    Pedestrian,
    RightOf,
    RoadBlockage,
    SceneObject,
    SchoolBus,
    Truck,
)
from src.graph.ontology import (
    AttributeValue,
    DetectionTarget,
    ObjectAttributeTarget,
    RelationTarget,
    RoadLayoutTarget,
)


DETECTION_TARGETS = (
    DetectionTarget(
        model=RoadBlockage,
        prompt='blocked road area',
    ),
    DetectionTarget(
        model=Bus,
        prompt='bus',
    ),
    DetectionTarget(
        model=Car,
        prompt='car',
    ),
    DetectionTarget(
        model=Cyclist,
        prompt='cyclist',
    ),
    DetectionTarget(
        model=Motorcycle,
        prompt='motorcycle',
    ),
    DetectionTarget(
        model=Pedestrian,
        prompt='pedestrian',
    ),
    DetectionTarget(
        model=SchoolBus,
        prompt='school bus',
    ),
    DetectionTarget(
        model=Truck,
        prompt='truck',
    ),
)


ROAD_LAYOUT_TARGETS = (
    RoadLayoutTarget(
        model=Lane,
        description="A semantic traffic lane relevant to ego's immediate driving situation.",
        membership_model=InLane,
        id_prefix='lane',
        attributes=(
            ObjectAttributeTarget(
                object_model=Lane,
                name='direction',
                description="Traffic direction in this lane relative to ego's direction.",
                required=True,
                values=(
                    AttributeValue(
                        value='same_as_ego',
                        description="Traffic travels approximately in ego's direction.",
                        prompt='Traffic in this lane travels in approximately the same direction as ego.',
                    ),
                    AttributeValue(
                        value='opposite_to_ego',
                        description="Traffic travels approximately opposite ego's direction.",
                        prompt='Traffic in this lane travels in approximately the opposite direction from ego.',
                    ),
                    AttributeValue(
                        value='crossing',
                        description="Traffic crosses ego's general direction.",
                        prompt="Traffic in this lane crosses ego's general direction.",
                    ),
                ),
            ),
        ),
    ),
)


RELATION_TARGETS = (
    RelationTarget(
        model=Behind,
        description="The subject is longitudinally behind ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        relation_extraction=True,
        road_layout_extraction=False,
        topology_constraint=None,
        symmetric=False,
    ),
    RelationTarget(
        model=InFrontOf,
        description="The subject is longitudinally ahead of ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        relation_extraction=True,
        road_layout_extraction=False,
        topology_constraint=None,
        symmetric=False,
    ),
    RelationTarget(
        model=InLane,
        description="The subject's ground reference point lies in the lane.",
        subject_model=SceneObject,
        object_model=Lane,
        exclusive_group='lane_membership',
        relation_extraction=False,
        road_layout_extraction=False,
        topology_constraint=None,
        symmetric=False,
    ),
    RelationTarget(
        model=LeftAdjacentTo,
        description='The subject is directly left of the object in ego-oriented road coordinates, with no physical separator between them.',
        subject_model=Lane,
        object_model=Lane,
        exclusive_group=None,
        relation_extraction=False,
        road_layout_extraction=True,
        topology_constraint='parallel_without_physical_separator',
        symmetric=False,
    ),
    RelationTarget(
        model=LeftOf,
        description="The subject is laterally left of ego relative to ego's road heading, not merely in the left half of the image.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        relation_extraction=True,
        road_layout_extraction=False,
        topology_constraint=None,
        symmetric=False,
    ),
    RelationTarget(
        model=Overlaps,
        description='The subject and object lanes have overlapping traffic paths.',
        subject_model=Lane,
        object_model=Lane,
        exclusive_group=None,
        relation_extraction=False,
        road_layout_extraction=True,
        topology_constraint=None,
        symmetric=True,
    ),
    RelationTarget(
        model=RightOf,
        description="The subject is laterally right of ego relative to ego's road heading, not merely in the right half of the image.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        relation_extraction=True,
        road_layout_extraction=False,
        topology_constraint=None,
        symmetric=False,
    ),
)


OBJECT_ATTRIBUTE_TARGETS = (
    ObjectAttributeTarget(
        object_model=SchoolBus,
        name='stop_arm_position',
        description='Visible position of the school bus stop arm.',
        required=False,
        values=(
            AttributeValue(
                value='deployed',
                description='The stop arm projects outward from the bus.',
                prompt='The stop arm is visibly extended outward from the side of the bus.',
            ),
            AttributeValue(
                value='stowed',
                description='The stop arm is folded against the bus.',
                prompt='The stop arm is visibly folded flat against the side of the bus.',
            ),
        ),
    ),
)
