# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.
# Do not edit this file directly.

from __future__ import annotations

from src.graph._generated.models import (
    Behind,
    Bus,
    Car,
    Cyclist,
    EgoVehicle,
    InFrontOf,
    InIntersection,
    InLane,
    Intersection,
    Lane,
    LeftOf,
    Motorcycle,
    Pedestrian,
    PerceivedRoadUser,
    RightOf,
    RoadUser,
    SchoolBus,
    StopArmState,
    Truck,
)
from src.graph.ontology import (
    DetectionTarget,
    RelationshipTarget,
    RoadRegionTarget,
    StateAttribute,
    StateTarget,
    StateValue,
)


DETECTION_TARGETS = (
    DetectionTarget(
        model=Bus,
        prompt='bus',
    ),
    DetectionTarget(
        model=Car,
        prompt='car',
    ),
    DetectionTarget(
        model=Cyclist,
        prompt='cyclist',
    ),
    DetectionTarget(
        model=Motorcycle,
        prompt='motorcycle',
    ),
    DetectionTarget(
        model=Pedestrian,
        prompt='pedestrian',
    ),
    DetectionTarget(
        model=SchoolBus,
        prompt='school bus',
    ),
    DetectionTarget(
        model=Truck,
        prompt='truck',
    ),
)


ROAD_REGION_TARGETS = (
    RoadRegionTarget(
        model=Intersection,
        description='A shared road region where traffic paths meet or cross.',
        membership_model=InIntersection,
        id_prefix='intersection',
    ),
    RoadRegionTarget(
        model=Lane,
        description='A visible road corridor for one line of traffic, independent of its direction relative to ego.',
        membership_model=InLane,
        id_prefix='lane',
    ),
)


RELATIONSHIP_TARGETS = (
    RelationshipTarget(
        model=Behind,
        description="The subject is longitudinally behind ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=PerceivedRoadUser,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        extraction_enabled=True,
    ),
    RelationshipTarget(
        model=InFrontOf,
        description="The subject is longitudinally ahead of ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=PerceivedRoadUser,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        extraction_enabled=True,
    ),
    RelationshipTarget(
        model=InIntersection,
        description="The subject's ground reference point lies in the intersection.",
        subject_model=RoadUser,
        object_model=Intersection,
        exclusive_group='intersection_membership',
        extraction_enabled=False,
    ),
    RelationshipTarget(
        model=InLane,
        description="The subject's ground reference point lies in the lane.",
        subject_model=RoadUser,
        object_model=Lane,
        exclusive_group='lane_membership',
        extraction_enabled=False,
    ),
    RelationshipTarget(
        model=LeftOf,
        description="The subject is laterally left of ego relative to ego's road heading, not merely in the left half of the image.",
        subject_model=PerceivedRoadUser,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        extraction_enabled=True,
    ),
    RelationshipTarget(
        model=RightOf,
        description="The subject is laterally right of ego relative to ego's road heading, not merely in the right half of the image.",
        subject_model=PerceivedRoadUser,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        extraction_enabled=True,
    ),
)


STATE_TARGETS = (
    StateTarget(
        model=StopArmState,
        description="An assertion about a school bus's mounted stop arm.",
        subject_model=SchoolBus,
        attributes=(
            StateAttribute(
                name='value',
                description='Asserted stop-arm position.',
                values=(
                    StateValue(
                        value='deployed',
                        description='The stop arm projects outward from the bus.',
                        prompt='The stop arm is visibly extended outward from the side of the bus.',
                    ),
                    StateValue(
                        value='stowed',
                        description='The stop arm is folded against the bus.',
                        prompt='The stop arm is visibly folded flat against the side of the bus.',
                    ),
                ),
            ),
        ),
    ),
)
