# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.
# Do not edit this file directly.

from __future__ import annotations

from src.graph._generated.models import (
    Animal,
    Behind,
    Bus,
    Car,
    ConstructionWorker,
    Cyclist,
    EgoVehicle,
    InFrontOf,
    InLane,
    Lane,
    LeftAdjacentTo,
    LeftOf,
    Motorcycle,
    Overlaps,
    Pedestrian,
    PoliceOfficer,
    RightOf,
    SceneObject,
    SchoolBus,
    Truck,
)
from src.graph.ontology import (
    AttributeValue,
    ObjectAttributeTarget,
    ObjectTarget,
    RelationTarget,
)

OBJECT_TARGETS = (
    ObjectTarget(
        model=Animal,
        description='A visible non-human animal that can affect traffic, including wild animals, domestic animals and livestock.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=Bus,
        description='A motorized vehicle designed to carry multiple passengers.',
        attributes=(
            ObjectAttributeTarget(
                object_model=Bus,
                name='opening_state',
                description='Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.',
                required=False,
                values=(
                    AttributeValue(
                        value='open',
                        description='At least one applicable vehicle opening is visibly open.',
                    ),
                    AttributeValue(
                        value='closed',
                        description='All applicable visible vehicle openings appear closed.',
                    ),
                ),
            ),
        ),
    ),
    ObjectTarget(
        model=Car,
        description='A motorized vehicle designed primarily for passenger transportation. A car typically has four wheels.',
        attributes=(
            ObjectAttributeTarget(
                object_model=Car,
                name='opening_state',
                description='Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.',
                required=False,
                values=(
                    AttributeValue(
                        value='open',
                        description='At least one applicable vehicle opening is visibly open.',
                    ),
                    AttributeValue(
                        value='closed',
                        description='All applicable visible vehicle openings appear closed.',
                    ),
                ),
            ),
        ),
    ),
    ObjectTarget(
        model=ConstructionWorker,
        description='A person visibly performing construction or maintenance work in the traffic scene.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=Cyclist,
        description='A person riding a bicycle.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=EgoVehicle,
        description='The observing vehicle and reference object for spatial relations.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=Lane,
        description="A semantic traffic lane relevant to ego's immediate driving situation.",
        attributes=(
            ObjectAttributeTarget(
                object_model=Lane,
                name='direction',
                description="Traffic direction in this lane relative to ego's direction.",
                required=True,
                values=(
                    AttributeValue(
                        value='same_as_ego',
                        description="Traffic travels approximately in ego's direction.",
                    ),
                    AttributeValue(
                        value='opposite_to_ego',
                        description="Traffic travels approximately opposite ego's direction.",
                    ),
                    AttributeValue(
                        value='crossing',
                        description="Traffic crosses ego's general direction.",
                    ),
                ),
            ),
        ),
    ),
    ObjectTarget(
        model=Motorcycle,
        description='A motorized vehicle designed primarily for passenger transportation on two or three wheels.',
        attributes=(
            ObjectAttributeTarget(
                object_model=Motorcycle,
                name='opening_state',
                description='Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.',
                required=False,
                values=(
                    AttributeValue(
                        value='open',
                        description='At least one applicable vehicle opening is visibly open.',
                    ),
                    AttributeValue(
                        value='closed',
                        description='All applicable visible vehicle openings appear closed.',
                    ),
                ),
            ),
        ),
    ),
    ObjectTarget(
        model=Pedestrian,
        description='A person on foot in the traffic scene.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=PoliceOfficer,
        description='A visibly identifiable police officer in the traffic scene.',
        attributes=(
        ),
    ),
    ObjectTarget(
        model=SchoolBus,
        description='A bus used to transport students.',
        attributes=(
            ObjectAttributeTarget(
                object_model=SchoolBus,
                name='stop_arm_position',
                description='Visible position of the school bus stop arm.',
                required=False,
                values=(
                    AttributeValue(
                        value='deployed',
                        description='The stop arm is visibly extended outward from the side of the bus.',
                    ),
                    AttributeValue(
                        value='stowed',
                        description='The stop arm is visibly folded flat against the side of the bus.',
                    ),
                ),
            ),
            ObjectAttributeTarget(
                object_model=SchoolBus,
                name='opening_state',
                description='Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.',
                required=False,
                values=(
                    AttributeValue(
                        value='open',
                        description='At least one applicable vehicle opening is visibly open.',
                    ),
                    AttributeValue(
                        value='closed',
                        description='All applicable visible vehicle openings appear closed.',
                    ),
                ),
            ),
        ),
    ),
    ObjectTarget(
        model=Truck,
        description='A motorized vehicle designed primarily to transport cargo.',
        attributes=(
            ObjectAttributeTarget(
                object_model=Truck,
                name='opening_state',
                description='Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.',
                required=False,
                values=(
                    AttributeValue(
                        value='open',
                        description='At least one applicable vehicle opening is visibly open.',
                    ),
                    AttributeValue(
                        value='closed',
                        description='All applicable visible vehicle openings appear closed.',
                    ),
                ),
            ),
        ),
    ),
)


RELATION_TARGETS = (
    RelationTarget(
        model=Behind,
        description="The subject is longitudinally behind ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        symmetric=False,
    ),
    RelationTarget(
        model=InFrontOf,
        description="The subject is longitudinally ahead of ego in road coordinates, regardless of the subject's facing or motion direction.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='longitudinal',
        symmetric=False,
    ),
    RelationTarget(
        model=InLane,
        description="The subject's ground reference point lies in the lane.",
        subject_model=SceneObject,
        object_model=Lane,
        exclusive_group='lane_membership',
        symmetric=False,
    ),
    RelationTarget(
        model=LeftAdjacentTo,
        description='The subject is directly left of the object in ego-oriented road coordinates, with no physical separator between them.',
        subject_model=Lane,
        object_model=Lane,
        exclusive_group=None,
        symmetric=False,
    ),
    RelationTarget(
        model=LeftOf,
        description="The subject is laterally left of ego relative to ego's road heading, not merely in the left half of the image.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        symmetric=False,
    ),
    RelationTarget(
        model=Overlaps,
        description='The subject and object lanes have overlapping traffic paths.',
        subject_model=Lane,
        object_model=Lane,
        exclusive_group=None,
        symmetric=True,
    ),
    RelationTarget(
        model=RightOf,
        description="The subject is laterally right of ego relative to ego's road heading, not merely in the right half of the image.",
        subject_model=SceneObject,
        object_model=EgoVehicle,
        exclusive_group='lateral',
        symmetric=False,
    ),
)
