# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.
# Do not edit this file directly.

from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Annotated,
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "0.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = None

class WeatherCondition(str, Enum):
    """
    A visible atmospheric condition expressed as one adjective.
    """
    clear = "clear"
    """
    The atmosphere has no visible precipitation, fog, or substantial cloud cover.
    """
    cloudy = "cloudy"
    """
    Clouds substantially cover the visible sky.
    """
    rainy = "rainy"
    """
    Rain is visibly present in the scene.
    """
    snowy = "snowy"
    """
    Snowfall is visibly present in the scene.
    """
    foggy = "foggy"
    """
    Fog visibly reduces atmospheric visibility.
    """


class ObjectDecision(str, Enum):
    """
    A decision bundled into an object record.
    """
    existence = "existence"
    """
    The object exists in the scene.
    """
    classification = "classification"
    """
    The object has the selected concrete type.
    """
    bounding_box = "bounding_box"
    """
    The object occupies the selected image bounding box.
    """
    tracking = "tracking"
    """
    The object has the selected cross-frame track identity.
    """
    attributes = "attributes"
    """
    The object has the selected object-specific attribute values.
    """


class VehicleOpeningState(str, Enum):
    """
    Visible state of the openable parts of a vehicle body.
    """
    open = "open"
    """
    At least one applicable vehicle opening is visibly open.
    """
    closed = "closed"
    """
    All applicable visible vehicle openings appear closed.
    """


class VehicleBodyOrientation(str, Enum):
    """
    Visible roll orientation of a vehicle body relative to its normal driving orientation.
    """
    upright = "upright"
    """
    The vehicle body has its normal upright roll orientation.
    """
    on_side = "on_side"
    """
    The vehicle body lies on either side.
    """
    upside_down = "upside_down"
    """
    The vehicle body is inverted from its normal upright orientation.
    """


class LaneDirection(str, Enum):
    """
    Traffic direction in a lane relative to ego's direction.
    """
    same_as_ego = "same_as_ego"
    """
    Traffic travels approximately in ego's direction.
    """
    opposite_to_ego = "opposite_to_ego"
    """
    Traffic travels approximately opposite ego's direction.
    """
    crossing = "crossing"
    """
    Traffic crosses ego's general direction.
    """


class StopArmPosition(str, Enum):
    """
    Supported positions of a school bus stop arm.
    """
    deployed = "deployed"
    """
    The stop arm is visibly extended outward from the side of the bus.
    """
    stowed = "stowed"
    """
    The stop arm is visibly folded flat against the side of the bus.
    """



class Provenance(ConfiguredBaseModel):
    """
    Coarse attribution for a decision represented in the scene graph.
    """
    source: str = Field(default=..., description="""Dataset, model, or algorithm that produced the decision.""")
    stage: str = Field(default=..., description="""Pipeline stage that added the decision to the normalized graph.""")
    model: Optional[str] = Field(default=None, description="""Exact model identifier when the source is a model.""")
    source_confidence: Optional[float] = Field(default=None, description="""Confidence reported by this source for its decision.""", ge=0, le=1)


class BoundingBox2D(ConfiguredBaseModel):
    """
    An axis-aligned image-space bounding box measured in pixels.
    """
    x_min: float = Field(default=..., description="""Minimum horizontal pixel coordinate.""", ge=0)
    y_min: float = Field(default=..., description="""Minimum vertical pixel coordinate.""", ge=0)
    x_max: float = Field(default=..., description="""Maximum horizontal pixel coordinate.""", ge=0)
    y_max: float = Field(default=..., description="""Maximum vertical pixel coordinate.""", ge=0)


class ObjectProvenance(Provenance):
    """
    Provenance that identifies the parts of an object record supported by a source.
    """
    supports: list[ObjectDecision] = Field(default=..., description="""Decisions in the object record supported by this source.""")
    source: str = Field(default=..., description="""Dataset, model, or algorithm that produced the decision.""")
    stage: str = Field(default=..., description="""Pipeline stage that added the decision to the normalized graph.""")
    model: Optional[str] = Field(default=None, description="""Exact model identifier when the source is a model.""")
    source_confidence: Optional[float] = Field(default=None, description="""Confidence reported by this source for its decision.""", ge=0, le=1)


class SceneObject(ConfiguredBaseModel):
    """
    An object represented in the scene graph.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["SceneObject"] = Field(default="SceneObject", description="""Concrete LinkML class of this object.""")
    bbox: Optional[BoundingBox2D] = Field(default=None, description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class PotentiallyMovingObject(SceneObject):
    """
    A visible object that takes an active or passive part in traffic.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["PotentiallyMovingObject"] = Field(default="PotentiallyMovingObject", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class EgoVehicle(SceneObject):
    """
    The observing vehicle and reference object for spatial relations.
    """
    id: Literal["ego"] = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["EgoVehicle"] = Field(default="EgoVehicle", description="""Concrete LinkML class of this object.""")
    bbox: Optional[BoundingBox2D] = Field(default=None, description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Vehicle(PotentiallyMovingObject):
    """
    A motorized vehicle represented in the traffic scene.
    """
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Vehicle"] = Field(default="Vehicle", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Car(Vehicle):
    """
    A motorized vehicle designed primarily for passenger transportation. A car typically has four wheels.
    """
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Car"] = Field(default="Car", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Truck(Vehicle):
    """
    A motorized vehicle designed primarily to transport cargo.
    """
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Truck"] = Field(default="Truck", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Bus(Vehicle):
    """
    A motorized vehicle designed to carry multiple passengers.
    """
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Bus"] = Field(default="Bus", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class SchoolBus(Bus):
    """
    A bus used to transport students.
    """
    stop_arm_position: Optional[StopArmPosition] = Field(default=None, description="""Visible position of the school bus stop arm.""")
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["SchoolBus"] = Field(default="SchoolBus", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Motorcycle(Vehicle):
    """
    A motorized vehicle designed primarily for passenger transportation on two or three wheels.
    """
    opening_state: Optional[VehicleOpeningState] = Field(default=None, description="""Visible state of the vehicle doors, hood, trunk, hatch, tailgate, or cargo doors.""")
    body_orientation: Optional[VehicleBodyOrientation] = Field(default=None, description="""Visible roll orientation of the vehicle body relative to its normal driving orientation.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Motorcycle"] = Field(default="Motorcycle", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Animal(PotentiallyMovingObject):
    """
    A visible non-human animal that can affect traffic, including wild animals, domestic animals and livestock.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Animal"] = Field(default="Animal", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Cyclist(PotentiallyMovingObject):
    """
    A person riding a bicycle.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Cyclist"] = Field(default="Cyclist", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Pedestrian(PotentiallyMovingObject):
    """
    A person on foot in the traffic scene.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Pedestrian"] = Field(default="Pedestrian", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class ConstructionWorker(PotentiallyMovingObject):
    """
    A person visibly performing construction or maintenance work in the traffic scene.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["ConstructionWorker"] = Field(default="ConstructionWorker", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class PoliceOfficer(PotentiallyMovingObject):
    """
    A visibly identifiable police officer in the traffic scene.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["PoliceOfficer"] = Field(default="PoliceOfficer", description="""Concrete LinkML class of this object.""")
    bbox: BoundingBox2D = Field(default=..., description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class RoadObject(SceneObject):
    """
    A road surface, road limitation, or road structure represented in the scene.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["RoadObject"] = Field(default="RoadObject", description="""Concrete LinkML class of this object.""")
    bbox: Optional[BoundingBox2D] = Field(default=None, description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Lane(RoadObject):
    """
    A semantic traffic lane relevant to ego's immediate driving situation.
    """
    direction: LaneDirection = Field(default=..., description="""Traffic direction in this lane relative to ego's direction.""")
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["Lane"] = Field(default="Lane", description="""Concrete LinkML class of this object.""")
    bbox: Optional[BoundingBox2D] = Field(default=None, description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class StaticObject(SceneObject):
    """
    A fixed landmark, traffic sign, sign board, or traffic light.
    """
    id: str = Field(default=..., description="""Identity used to reference this object within the scene.""")
    type: Literal["StaticObject"] = Field(default="StaticObject", description="""Concrete LinkML class of this object.""")
    bbox: Optional[BoundingBox2D] = Field(default=None, description="""Optional image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical object.""")
    provenance: list[ObjectProvenance] = Field(default=..., description="""Sources that support decisions in this object record.""")


class Relation(ConfiguredBaseModel):
    """
    An abstract relation between two objects in the scene graph.
    """
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["Relation"] = Field(default="Relation", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class SpatialRelation(Relation):
    """
    An abstract road-coordinate relation from a scene object to ego.
    """
    subject: str = Field(default=..., description="""Scene object described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["SpatialRelation"] = Field(default="SpatialRelation", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class InFrontOf(SpatialRelation):
    """
    The subject is longitudinally ahead of ego in road coordinates, regardless of the subject's facing or motion direction.
    """
    subject: str = Field(default=..., description="""Scene object described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["InFrontOf"] = Field(default="InFrontOf", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class Behind(SpatialRelation):
    """
    The subject is longitudinally behind ego in road coordinates, regardless of the subject's facing or motion direction.
    """
    subject: str = Field(default=..., description="""Scene object described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["Behind"] = Field(default="Behind", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class LeftOf(SpatialRelation):
    """
    The subject is laterally left of ego relative to ego's road heading, not merely in the left half of the image.
    """
    subject: str = Field(default=..., description="""Scene object described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["LeftOf"] = Field(default="LeftOf", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class RightOf(SpatialRelation):
    """
    The subject is laterally right of ego relative to ego's road heading, not merely in the right half of the image.
    """
    subject: str = Field(default=..., description="""Scene object described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["RightOf"] = Field(default="RightOf", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class RoadObjectRelation(Relation):
    """
    An abstract relation from a scene object to a road object.
    """
    subject: str = Field(default=..., description="""Scene object located in the road object.""")
    object: str = Field(default=..., description="""Road object that contains the subject's ground reference point.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["RoadObjectRelation"] = Field(default="RoadObjectRelation", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class InLane(RoadObjectRelation):
    """
    The subject's ground reference point lies in the lane.
    """
    subject: str = Field(default=..., description="""Scene object located in the road object.""")
    object: str = Field(default=..., description="""Road object that contains the subject's ground reference point.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["InLane"] = Field(default="InLane", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class LaneRelation(Relation):
    """
    An abstract topological relation between two lanes.
    """
    subject: str = Field(default=..., description="""Lane from which the topological relation is stated.""")
    object: str = Field(default=..., description="""Lane related to the subject lane.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["LaneRelation"] = Field(default="LaneRelation", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class LeftAdjacentTo(LaneRelation):
    """
    The subject is directly left of the object in ego-oriented road coordinates, with no physical separator between them.
    """
    subject: str = Field(default=..., description="""Lane from which the topological relation is stated.""")
    object: str = Field(default=..., description="""Lane related to the subject lane.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["LeftAdjacentTo"] = Field(default="LeftAdjacentTo", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class Overlaps(LaneRelation):
    """
    The subject and object lanes have overlapping traffic paths.
    """
    subject: str = Field(default=..., description="""Lane from which the topological relation is stated.""")
    object: str = Field(default=..., description="""Lane related to the subject lane.""")
    id: str = Field(default=..., description="""Identity of this relation within the scene.""")
    type: Literal["Overlaps"] = Field(default="Overlaps", description="""Concrete LinkML class of this relation.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relation assertion.""")


class Scene(ConfiguredBaseModel):
    """
    A road scene corresponding to one input frame.
    """
    frame_id: str = Field(default=..., description="""Frame-local identifier assigned by the input stage.""")
    timestamp_ns: Optional[int] = Field(default=None, description="""Optional source timestamp in nanoseconds.""", ge=0)
    provenance: list[Provenance] = Field(default=..., description="""Sources that contributed the frame represented by this scene.""")
    weather: Optional[WeatherCondition] = Field(default=None, description="""Visible atmospheric condition for this scene.""")
    objects: list[Annotated[Union[Animal,Bus,Car,ConstructionWorker,Cyclist,EgoVehicle,Lane,Motorcycle,Pedestrian,PoliceOfficer,SchoolBus,Truck], Field(discriminator="type")]] = Field(default=..., description="""Potentially moving, road, and static objects represented in the scene.""")
    relations: list[Annotated[Union[Behind,InFrontOf,InLane,LeftAdjacentTo,LeftOf,Overlaps,RightOf], Field(discriminator="type")]] = Field(default=..., description="""Relations between objects represented in the scene.""")


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Provenance.model_rebuild()
BoundingBox2D.model_rebuild()
ObjectProvenance.model_rebuild()
SceneObject.model_rebuild()
PotentiallyMovingObject.model_rebuild()
EgoVehicle.model_rebuild()
Vehicle.model_rebuild()
Car.model_rebuild()
Truck.model_rebuild()
Bus.model_rebuild()
SchoolBus.model_rebuild()
Motorcycle.model_rebuild()
Animal.model_rebuild()
Cyclist.model_rebuild()
Pedestrian.model_rebuild()
ConstructionWorker.model_rebuild()
PoliceOfficer.model_rebuild()
RoadObject.model_rebuild()
Lane.model_rebuild()
StaticObject.model_rebuild()
Relation.model_rebuild()
SpatialRelation.model_rebuild()
InFrontOf.model_rebuild()
Behind.model_rebuild()
LeftOf.model_rebuild()
RightOf.model_rebuild()
RoadObjectRelation.model_rebuild()
InLane.model_rebuild()
LaneRelation.model_rebuild()
LeftAdjacentTo.model_rebuild()
Overlaps.model_rebuild()
Scene.model_rebuild()
