# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.
# Do not edit this file directly.

from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Annotated,
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "0.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = None

class WeatherCondition(str, Enum):
    """
    A visible atmospheric condition expressed as one adjective.
    """
    clear = "clear"
    """
    The atmosphere has no visible precipitation, fog, or substantial cloud cover.
    """
    cloudy = "cloudy"
    """
    Clouds substantially cover the visible sky.
    """
    rainy = "rainy"
    """
    Rain is visibly present in the scene.
    """
    snowy = "snowy"
    """
    Snowfall is visibly present in the scene.
    """
    foggy = "foggy"
    """
    Fog visibly reduces atmospheric visibility.
    """


class RoadUserDecision(str, Enum):
    """
    A decision bundled into a perceived road-user record.
    """
    existence = "existence"
    """
    The road user exists in the scene.
    """
    classification = "classification"
    """
    The road user has the selected concrete type.
    """
    bounding_box = "bounding_box"
    """
    The road user occupies the selected image bounding box.
    """
    tracking = "tracking"
    """
    The road user has the selected cross-frame track identity.
    """


class StopArmStateValue(str, Enum):
    """
    Supported positions of a school bus's mounted stop arm.
    """
    deployed = "deployed"
    """
    The stop arm projects outward from the bus.
    """
    stowed = "stowed"
    """
    The stop arm is folded against the bus.
    """



class Provenance(ConfiguredBaseModel):
    """
    Coarse attribution for a decision represented in the scene graph.
    """
    source: str = Field(default=..., description="""Dataset, model, or algorithm that produced the decision.""")
    stage: str = Field(default=..., description="""Pipeline stage that added the decision to the normalized graph.""")
    model: Optional[str] = Field(default=None, description="""Exact model identifier when the source is a model.""")
    source_confidence: Optional[float] = Field(default=None, description="""Confidence reported by this source for its decision.""", ge=0, le=1)


class BoundingBox2D(ConfiguredBaseModel):
    """
    An axis-aligned image-space bounding box measured in pixels.
    """
    x_min: float = Field(default=..., description="""Minimum horizontal pixel coordinate.""", ge=0)
    y_min: float = Field(default=..., description="""Minimum vertical pixel coordinate.""", ge=0)
    x_max: float = Field(default=..., description="""Maximum horizontal pixel coordinate.""", ge=0)
    y_max: float = Field(default=..., description="""Maximum vertical pixel coordinate.""", ge=0)


class RoadUserProvenance(Provenance):
    """
    Provenance identifying the parts of a perceived road-user record supported by a source.
    """
    supports: list[RoadUserDecision] = Field(default=..., description="""Decisions in the road-user record supported by this source.""")
    source: str = Field(default=..., description="""Dataset, model, or algorithm that produced the decision.""")
    stage: str = Field(default=..., description="""Pipeline stage that added the decision to the normalized graph.""")
    model: Optional[str] = Field(default=None, description="""Exact model identifier when the source is a model.""")
    source_confidence: Optional[float] = Field(default=None, description="""Confidence reported by this source for its decision.""", ge=0, le=1)


class RoadUser(ConfiguredBaseModel):
    """
    A traffic participant represented in the scene graph.
    """
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["RoadUser"] = Field(default="RoadUser", description="""Concrete LinkML class of this road user.""")


class EgoVehicle(RoadUser):
    """
    The observing vehicle and reference frame for spatial relationships.
    """
    provenance: list[Provenance] = Field(default=..., description="""Source establishing ego for this scene.""")
    id: Literal["ego"] = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["EgoVehicle"] = Field(default="EgoVehicle", description="""Concrete LinkML class of this road user.""")


class PerceivedRoadUser(RoadUser):
    """
    A non-ego road user localized in the input image.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["PerceivedRoadUser"] = Field(default="PerceivedRoadUser", description="""Concrete LinkML class of this road user.""")


class Vehicle(PerceivedRoadUser):
    """
    An abstract perceived motor vehicle.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Vehicle"] = Field(default="Vehicle", description="""Concrete LinkML class of this road user.""")


class Car(Vehicle):
    """
    A passenger car.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Car"] = Field(default="Car", description="""Concrete LinkML class of this road user.""")


class Truck(Vehicle):
    """
    A truck.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Truck"] = Field(default="Truck", description="""Concrete LinkML class of this road user.""")


class Bus(Vehicle):
    """
    A passenger bus that is not necessarily a school bus.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Bus"] = Field(default="Bus", description="""Concrete LinkML class of this road user.""")


class SchoolBus(Bus):
    """
    A bus used to transport students.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["SchoolBus"] = Field(default="SchoolBus", description="""Concrete LinkML class of this road user.""")


class Motorcycle(Vehicle):
    """
    A motorcycle.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Motorcycle"] = Field(default="Motorcycle", description="""Concrete LinkML class of this road user.""")


class Cyclist(PerceivedRoadUser):
    """
    A person riding a bicycle.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Cyclist"] = Field(default="Cyclist", description="""Concrete LinkML class of this road user.""")


class Pedestrian(PerceivedRoadUser):
    """
    A person traveling on foot.
    """
    bbox: BoundingBox2D = Field(default=..., description="""Image-space bounding box in pixel XYXY coordinates.""")
    track_id: Optional[str] = Field(default=None, description="""Optional cross-frame identity for the same physical road user.""")
    provenance: list[RoadUserProvenance] = Field(default=..., description="""Sources supporting the existence, classification, bounding box, or tracking decisions.""")
    id: str = Field(default=..., description="""Identity used to reference this road user within the scene.""")
    type: Literal["Pedestrian"] = Field(default="Pedestrian", description="""Concrete LinkML class of this road user.""")


class ObjectState(ConfiguredBaseModel):
    """
    An abstract provenance-carrying state observed on a perceived road user.
    """
    type: Literal["ObjectState"] = Field(default="ObjectState", description="""Concrete LinkML class of this object state.""")
    subject: str = Field(default=..., description="""Perceived road user whose state is being described.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources supporting the state assertion.""")


class StopArmState(ObjectState):
    """
    An assertion about a school bus's mounted stop arm.
    """
    value: StopArmStateValue = Field(default=..., description="""Asserted stop-arm position.""")
    type: Literal["StopArmState"] = Field(default="StopArmState", description="""Concrete LinkML class of this object state.""")
    subject: str = Field(default=..., description="""Perceived road user whose state is being described.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources supporting the state assertion.""")


class RoadRegion(ConfiguredBaseModel):
    """
    An image-derived road surface region represented in the scene graph.
    """
    id: str = Field(default=..., description="""Identity used to reference this road region within the scene.""")
    type: Literal["RoadRegion"] = Field(default="RoadRegion", description="""Concrete LinkML class of this road region.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the existence and classification of this road region.""")


class Lane(RoadRegion):
    """
    A visible road corridor for one line of traffic, independent of its direction relative to ego.
    """
    id: str = Field(default=..., description="""Identity used to reference this road region within the scene.""")
    type: Literal["Lane"] = Field(default="Lane", description="""Concrete LinkML class of this road region.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the existence and classification of this road region.""")


class Intersection(RoadRegion):
    """
    A shared road region where traffic paths meet or cross.
    """
    id: str = Field(default=..., description="""Identity used to reference this road region within the scene.""")
    type: Literal["Intersection"] = Field(default="Intersection", description="""Concrete LinkML class of this road region.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the existence and classification of this road region.""")


class Relationship(ConfiguredBaseModel):
    """
    An abstract relationship between two entities in the scene graph.
    """
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["Relationship"] = Field(default="Relationship", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class SpatialRelationship(Relationship):
    """
    An abstract road-coordinate relationship from a perceived road user to ego.
    """
    subject: str = Field(default=..., description="""Perceived road user described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["SpatialRelationship"] = Field(default="SpatialRelationship", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class InFrontOf(SpatialRelationship):
    """
    The subject is longitudinally ahead of ego in road coordinates, regardless of the subject's facing or motion direction.
    """
    subject: str = Field(default=..., description="""Perceived road user described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["InFrontOf"] = Field(default="InFrontOf", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class Behind(SpatialRelationship):
    """
    The subject is longitudinally behind ego in road coordinates, regardless of the subject's facing or motion direction.
    """
    subject: str = Field(default=..., description="""Perceived road user described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["Behind"] = Field(default="Behind", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class LeftOf(SpatialRelationship):
    """
    The subject is laterally left of ego relative to ego's road heading, not merely in the left half of the image.
    """
    subject: str = Field(default=..., description="""Perceived road user described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["LeftOf"] = Field(default="LeftOf", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class RightOf(SpatialRelationship):
    """
    The subject is laterally right of ego relative to ego's road heading, not merely in the right half of the image.
    """
    subject: str = Field(default=..., description="""Perceived road user described relative to ego.""")
    object: str = Field(default=..., description="""Ego vehicle used as the spatial reference.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["RightOf"] = Field(default="RightOf", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class RoadRegionRelationship(Relationship):
    """
    An abstract relationship from a road user to a road region.
    """
    subject: str = Field(default=..., description="""Road user located in the road region.""")
    object: str = Field(default=..., description="""Road region that contains the road user's ground reference point.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["RoadRegionRelationship"] = Field(default="RoadRegionRelationship", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class InLane(RoadRegionRelationship):
    """
    The subject's ground reference point lies in the lane.
    """
    subject: str = Field(default=..., description="""Road user located in the road region.""")
    object: str = Field(default=..., description="""Road region that contains the road user's ground reference point.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["InLane"] = Field(default="InLane", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class InIntersection(RoadRegionRelationship):
    """
    The subject's ground reference point lies in the intersection.
    """
    subject: str = Field(default=..., description="""Road user located in the road region.""")
    object: str = Field(default=..., description="""Road region that contains the road user's ground reference point.""")
    id: str = Field(default=..., description="""Identity of this relationship within the scene.""")
    type: Literal["InIntersection"] = Field(default="InIntersection", description="""Concrete LinkML class of this relationship.""")
    provenance: list[Provenance] = Field(default=..., description="""Sources that support the relationship assertion.""")


class Scene(ConfiguredBaseModel):
    """
    A road scene corresponding to one input frame.
    """
    frame_id: str = Field(default=..., description="""Frame-local identifier assigned by the input stage.""")
    timestamp_ns: Optional[int] = Field(default=None, description="""Optional source timestamp in nanoseconds.""", ge=0)
    provenance: list[Provenance] = Field(default=..., description="""Sources that contributed the frame represented by this scene.""")
    ego: EgoVehicle = Field(default=..., description="""The observing vehicle, which is not represented by an image bounding box.""")
    weather: Optional[WeatherCondition] = Field(default=None, description="""Visible atmospheric condition for this scene.""")
    road_users: Optional[list[Annotated[Union[Bus,Car,Cyclist,Motorcycle,Pedestrian,SchoolBus,Truck], Field(discriminator="type")]]] = Field(default=None, description="""Road users perceived in the frame, excluding ego.""")
    road_regions: Optional[list[Annotated[Union[Intersection,Lane], Field(discriminator="type")]]] = Field(default=None, description="""Road regions perceived in the frame.""")
    states: Optional[list[StopArmState]] = Field(default=None, description="""States observed on perceived road users in this frame.""")
    relationships: Optional[list[Annotated[Union[Behind,InFrontOf,InIntersection,InLane,LeftOf,RightOf], Field(discriminator="type")]]] = Field(default=None, description="""Relationships between entities represented in the scene.""")


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Provenance.model_rebuild()
BoundingBox2D.model_rebuild()
RoadUserProvenance.model_rebuild()
RoadUser.model_rebuild()
EgoVehicle.model_rebuild()
PerceivedRoadUser.model_rebuild()
Vehicle.model_rebuild()
Car.model_rebuild()
Truck.model_rebuild()
Bus.model_rebuild()
SchoolBus.model_rebuild()
Motorcycle.model_rebuild()
Cyclist.model_rebuild()
Pedestrian.model_rebuild()
ObjectState.model_rebuild()
StopArmState.model_rebuild()
RoadRegion.model_rebuild()
Lane.model_rebuild()
Intersection.model_rebuild()
Relationship.model_rebuild()
SpatialRelationship.model_rebuild()
InFrontOf.model_rebuild()
Behind.model_rebuild()
LeftOf.model_rebuild()
RightOf.model_rebuild()
RoadRegionRelationship.model_rebuild()
InLane.model_rebuild()
InIntersection.model_rebuild()
Scene.model_rebuild()
