from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from linkml.generators.pydanticgen import PydanticGenerator
from linkml.generators.pydanticgen.pydanticgen import MetadataMode
from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "scene_graph.yaml"
GENERATED_DIRECTORY = ROOT / "src" / "graph" / "_generated"
MODELS_PATH = GENERATED_DIRECTORY / "models.py"
CATALOG_PATH = GENERATED_DIRECTORY / "catalog.py"
GENERATED_HEADER = (
    "# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.\n"
    "# Do not edit this file directly.\n\n"
)


def main() -> int:
    print(f"[schema] compile started: {SCHEMA_PATH.relative_to(ROOT)}")
    view = SchemaView(str(SCHEMA_PATH))
    models = PydanticGenerator(
        SCHEMA_PATH,
        metadata_mode=MetadataMode.NONE,
        extra_fields="forbid",
    ).serialize()
    models = _restrict_scene_collections(models, view)
    catalog = _catalog_source(view)

    GENERATED_DIRECTORY.mkdir(parents=True, exist_ok=True)
    _write(MODELS_PATH, GENERATED_HEADER + models)
    _write(CATALOG_PATH, GENERATED_HEADER + catalog)
    print("[schema] compile finished")
    return 0


def _catalog_source(view: SchemaView) -> str:
    concrete_objects = _concrete_descendants(view, "SceneObject")
    concrete_relations = _concrete_descendants(view, "Relation")

    object_attributes = _attribute_targets(view, concrete_objects)
    object_targets = []
    for name in concrete_objects:
        definition = _required_class(view, name)
        object_targets.append(
            (
                name,
                _description(definition, name),
                tuple(
                    target
                    for target in object_attributes
                    if target[0] == name
                ),
            )
        )

    relation_targets = []
    for name in concrete_relations:
        definition = _required_class(view, name)
        subject_range = str(view.induced_slot("subject", name).range)
        object_range = str(view.induced_slot("object", name).range)
        relation_targets.append(
            (
                name,
                _description(definition, name),
                subject_range,
                object_range,
                _annotation(definition, "exclusive_group"),
                _annotation(definition, "symmetric") == "enabled",
            )
        )
    model_names = {
        *concrete_objects,
        *concrete_relations,
        *(item for target in relation_targets for item in target[:1] + target[2:4]),
        *(target[0] for target in object_attributes),
    }

    lines = [
        "from __future__ import annotations",
        "",
        "from src.graph._generated.models import (",
        *(f"    {name}," for name in sorted(model_names)),
        ")",
        "from src.graph.ontology import (",
        "    AttributeValue,",
        "    ObjectAttributeTarget,",
        "    ObjectTarget,",
        "    RelationTarget,",
        ")",
        "",
        "OBJECT_TARGETS = (",
    ]
    for name, description, attributes in sorted(object_targets):
        lines.extend(
            [
                "    ObjectTarget(",
                f"        model={name},",
                f"        description={description!r},",
                "        attributes=(",
            ]
        )
        _append_attribute_targets(lines, attributes, indent="            ")
        lines.extend(["        ),", "    ),"])
    lines.extend([")", "", "", "RELATION_TARGETS = ("])
    for (
        name,
        description,
        subject_range,
        object_range,
        exclusive_group,
        symmetric,
    ) in sorted(relation_targets):
        lines.extend(
            [
                "    RelationTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        subject_model={subject_range},",
                f"        object_model={object_range},",
                f"        exclusive_group={exclusive_group!r},",
                f"        symmetric={symmetric!r},",
                "    ),",
            ]
        )
    lines.extend([")", ""])
    return "\n".join(lines)


def _attribute_targets(
    view: SchemaView,
    concrete_objects: tuple[str, ...],
) -> list[tuple[str, str, str, bool, list[tuple[str, str]]]]:
    targets = []
    system_fields = {"id", "type", "bbox", "track_id", "provenance"}
    for name in concrete_objects:
        declared_slots: dict[str, Any] = {}
        for ancestor in view.class_ancestors(name, reflexive=True):
            definition = _required_class(view, str(ancestor))
            for slot in definition.attributes.values():
                declared_slots.setdefault(str(slot.name), slot)
        for slot_name, slot in declared_slots.items():
            if slot_name in system_fields:
                continue
            enum_definition = view.get_enum(slot.range)
            if enum_definition is None:
                continue
            if slot.multivalued:
                raise ValueError(
                    f"Enum object attribute {name}.{slot_name} cannot be multivalued"
                )
            values = [
                (str(value), permissible.description or str(value))
                for value, permissible in enum_definition.permissible_values.items()
            ]
            targets.append(
                (
                    name,
                    slot_name,
                    slot.description or enum_definition.description or slot_name,
                    slot.required is True,
                    values,
                )
            )
    return targets


def _append_attribute_targets(
    lines: list[str],
    targets: Any,
    *,
    indent: str,
) -> None:
    for model_name, name, description, required, values in targets:
        lines.extend(
            [
                f"{indent}ObjectAttributeTarget(",
                f"{indent}    object_model={model_name},",
                f"{indent}    name={name!r},",
                f"{indent}    description={description!r},",
                f"{indent}    required={required!r},",
                f"{indent}    values=(",
            ]
        )
        for value, value_description in values:
            lines.extend(
                [
                    f"{indent}        AttributeValue(",
                    f"{indent}            value={value!r},",
                    f"{indent}            description={value_description!r},",
                    f"{indent}        ),",
                ]
            )
        lines.extend([f"{indent}    ),", f"{indent}),"])


def _restrict_scene_collections(models: str, view: SchemaView) -> str:
    collection_models = {
        "objects": _concrete_descendants(view, "SceneObject"),
        "relations": _concrete_descendants(view, "Relation"),
    }
    uses_annotated = False
    for field_name, model_names in collection_models.items():
        if not model_names:
            raise ValueError(f"Scene.{field_name} has no concrete model types")
        if len(model_names) == 1:
            value_annotation = model_names[0]
        else:
            union = ",".join(model_names)
            value_annotation = (
                f'Annotated[Union[{union}], Field(discriminator="type")]'
            )
            uses_annotated = True
        pattern = re.compile(
            rf"^(    {field_name}: )list\[Union\[[^\n]+\]\]( = Field\()",
            re.MULTILINE,
        )
        models, replacements = pattern.subn(
            rf"\g<1>list[{value_annotation}]\g<2>", models
        )
        if replacements != 1:
            raise ValueError(
                f"Expected one generated Scene.{field_name} union, "
                f"found {replacements}"
            )

    if uses_annotated:
        models, replacements = re.subn(
            r"(from typing import \(\n)",
            r"\1    Annotated,\n",
            models,
            count=1,
        )
        if replacements != 1:
            raise ValueError("Generated models have no typing import block")
    return models


def _concrete_descendants(view: SchemaView, parent: str) -> tuple[str, ...]:
    names = view.class_descendants(parent, reflexive=False)
    return tuple(
        sorted(
            str(name)
            for name in names
            if _required_class(view, str(name)).abstract is not True
        )
    )


def _required_class(view: SchemaView, name: str) -> Any:
    definition = view.get_class(name)
    if definition is None:
        raise ValueError(f"Unknown LinkML class: {name}")
    return definition


def _annotation(element: Any, name: str) -> str | None:
    annotations = element.annotations
    if name not in annotations:
        return None
    annotation = annotations[name]
    value = annotation.value
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"LinkML annotation {name} must be a nonempty string")
    return value.strip()


def _description(definition: Any, name: str) -> str:
    description = definition.description
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"LinkML class {name} needs a description")
    return description.strip()


def _write(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    print(f"[schema] wrote: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    raise SystemExit(main())
