from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from linkml.generators.pydanticgen import PydanticGenerator
from linkml.generators.pydanticgen.pydanticgen import MetadataMode
from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "scene_graph.yaml"
GENERATED_DIRECTORY = ROOT / "src" / "graph" / "_generated"
MODELS_PATH = GENERATED_DIRECTORY / "models.py"
CATALOG_PATH = GENERATED_DIRECTORY / "catalog.py"
GENERATED_HEADER = (
    "# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.\n"
    "# Do not edit this file directly.\n\n"
)


def main() -> int:
    print(f"[schema] compile started: {SCHEMA_PATH.relative_to(ROOT)}")
    view = SchemaView(str(SCHEMA_PATH))
    models = PydanticGenerator(
        SCHEMA_PATH,
        metadata_mode=MetadataMode.NONE,
        extra_fields="forbid",
    ).serialize()
    models = _restrict_scene_collections(models, view)
    catalog = _catalog_source(view)

    GENERATED_DIRECTORY.mkdir(parents=True, exist_ok=True)
    _write(MODELS_PATH, GENERATED_HEADER + models)
    _write(CATALOG_PATH, GENERATED_HEADER + catalog)
    print("[schema] compile finished")
    return 0


def _catalog_source(view: SchemaView) -> str:
    concrete_objects = _concrete_descendants(view, "SceneObject")
    concrete_relations = _concrete_descendants(view, "Relation")

    detection_targets = []
    for name in concrete_objects:
        prompt = _annotation(view.get_class(name), "object_detection_prompt")
        if prompt is not None:
            detection_targets.append((name, prompt))
    prompts: dict[str, str] = {}
    for name, prompt in detection_targets:
        previous = prompts.get(prompt.casefold())
        if previous is not None:
            raise ValueError(
                f"Detection prompt {prompt!r} belongs to both {previous} and {name}"
            )
        prompts[prompt.casefold()] = name

    relation_targets = []
    membership_by_object_range: dict[str, list[str]] = {}
    road_object_relations = set(
        _concrete_descendants(view, "RoadObjectRelation")
    )
    for name in concrete_relations:
        definition = _required_class(view, name)
        subject_range = str(view.induced_slot("subject", name).range)
        object_range = str(view.induced_slot("object", name).range)
        relation_targets.append(
            (
                name,
                _description(definition, name),
                subject_range,
                object_range,
                _annotation(definition, "exclusive_group"),
                _annotation(definition, "relation_extraction") == "enabled",
                _annotation(definition, "road_layout_extraction") == "enabled",
                _annotation(definition, "topology_constraint"),
                _annotation(definition, "symmetric") == "enabled",
            )
        )
        if name in road_object_relations:
            membership_by_object_range.setdefault(object_range, []).append(name)

    road_layout_attributes = _attribute_targets(
        view,
        concrete_objects,
        extraction_annotation="road_layout_extraction",
    )
    relation_attributes = _attribute_targets(
        view,
        concrete_objects,
        extraction_annotation="relation_extraction",
    )

    road_layout_targets = []
    for name in _concrete_descendants(view, "RoadObject"):
        definition = _required_class(view, name)
        if _annotation(definition, "road_layout_extraction") != "enabled":
            continue
        memberships = membership_by_object_range.get(name, [])
        if len(memberships) != 1:
            raise ValueError(
                f"Road layout object {name} needs exactly one membership relation, "
                f"found {memberships}"
            )
        road_layout_targets.append(
            (
                name,
                _description(definition, name),
                memberships[0],
                _snake_case(name),
                tuple(
                    target
                    for target in road_layout_attributes
                    if target[0] == name
                ),
            )
        )

    model_names = {
        *concrete_objects,
        *concrete_relations,
        *(name for name, _ in detection_targets),
        *(item for target in relation_targets for item in target[:1] + target[2:4]),
        *(item for target in road_layout_targets for item in target[:1] + target[2:3]),
        *(target[0] for target in road_layout_attributes),
        *(target[0] for target in relation_attributes),
    }

    lines = [
        "from __future__ import annotations",
        "",
        "from src.graph._generated.models import (",
        *(f"    {name}," for name in sorted(model_names)),
        ")",
        "from src.graph.ontology import (",
        "    AttributeValue,",
        "    DetectionTarget,",
        "    ObjectAttributeTarget,",
        "    RelationTarget,",
        "    RoadLayoutTarget,",
        ")",
        "",
        "",
        "DETECTION_TARGETS = (",
    ]
    for name, prompt in sorted(detection_targets, key=lambda item: item[1].casefold()):
        lines.extend(
            [
                "    DetectionTarget(",
                f"        model={name},",
                f"        prompt={prompt!r},",
                "    ),",
            ]
        )
    lines.extend([")", "", "", "ROAD_LAYOUT_TARGETS = ("])
    for name, description, membership, prefix, attributes in sorted(
        road_layout_targets
    ):
        lines.extend(
            [
                "    RoadLayoutTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        membership_model={membership},",
                f"        id_prefix={prefix!r},",
                "        attributes=(",
            ]
        )
        _append_attribute_targets(lines, attributes, indent="            ")
        lines.extend(["        ),", "    ),"])
    lines.extend([")", "", "", "RELATION_TARGETS = ("])
    for (
        name,
        description,
        subject_range,
        object_range,
        exclusive_group,
        relation_extraction,
        road_layout_extraction,
        topology_constraint,
        symmetric,
    ) in sorted(relation_targets):
        lines.extend(
            [
                "    RelationTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        subject_model={subject_range},",
                f"        object_model={object_range},",
                f"        exclusive_group={exclusive_group!r},",
                f"        relation_extraction={relation_extraction!r},",
                f"        road_layout_extraction={road_layout_extraction!r},",
                f"        topology_constraint={topology_constraint!r},",
                f"        symmetric={symmetric!r},",
                "    ),",
            ]
        )
    lines.extend([")", "", "", "OBJECT_ATTRIBUTE_TARGETS = ("])
    _append_attribute_targets(lines, relation_attributes, indent="    ")
    lines.extend([")", ""])
    return "\n".join(lines)


def _attribute_targets(
    view: SchemaView,
    concrete_objects: tuple[str, ...],
    *,
    extraction_annotation: str,
) -> list[tuple[str, str, str, bool, list[tuple[str, str, str]]]]:
    targets = []
    prompt_annotation = extraction_annotation + "_prompt"
    system_fields = {"id", "type", "bbox", "track_id", "provenance"}
    for name in concrete_objects:
        declared_slots: dict[str, Any] = {}
        for ancestor in view.class_ancestors(name, reflexive=True):
            definition = _required_class(view, str(ancestor))
            for slot in definition.attributes.values():
                declared_slots.setdefault(str(slot.name), slot)
        for slot_name, slot in declared_slots.items():
            if slot_name in system_fields:
                continue
            if _annotation(slot, extraction_annotation) != "enabled":
                continue
            if slot.multivalued:
                raise ValueError(
                    f"Extracted object attribute {name}.{slot_name} cannot be multivalued"
                )
            enum_definition = view.get_enum(slot.range)
            if enum_definition is None:
                raise ValueError(
                    f"Extracted object attribute {name}.{slot_name} must use an enum"
                )
            values = []
            for value, permissible in enum_definition.permissible_values.items():
                prompt = _annotation(permissible, prompt_annotation)
                if prompt is None:
                    raise ValueError(
                        f"Attribute value {enum_definition.name}.{value} needs a "
                        f"{prompt_annotation} annotation"
                    )
                values.append(
                    (
                        str(value),
                        permissible.description or str(value),
                        prompt,
                    )
                )
            targets.append(
                (
                    name,
                    slot_name,
                    slot.description or enum_definition.description or slot_name,
                    slot.required is True,
                    values,
                )
            )
    return targets


def _append_attribute_targets(
    lines: list[str],
    targets: Any,
    *,
    indent: str,
) -> None:
    for model_name, name, description, required, values in targets:
        lines.extend(
            [
                f"{indent}ObjectAttributeTarget(",
                f"{indent}    object_model={model_name},",
                f"{indent}    name={name!r},",
                f"{indent}    description={description!r},",
                f"{indent}    required={required!r},",
                f"{indent}    values=(",
            ]
        )
        for value, value_description, prompt in values:
            lines.extend(
                [
                    f"{indent}        AttributeValue(",
                    f"{indent}            value={value!r},",
                    f"{indent}            description={value_description!r},",
                    f"{indent}            prompt={prompt!r},",
                    f"{indent}        ),",
                ]
            )
        lines.extend([f"{indent}    ),", f"{indent}),"])


def _restrict_scene_collections(models: str, view: SchemaView) -> str:
    collection_models = {
        "objects": _concrete_descendants(view, "SceneObject"),
        "relations": _concrete_descendants(view, "Relation"),
    }
    uses_annotated = False
    for field_name, model_names in collection_models.items():
        if not model_names:
            raise ValueError(f"Scene.{field_name} has no concrete model types")
        if len(model_names) == 1:
            value_annotation = model_names[0]
        else:
            union = ",".join(model_names)
            value_annotation = (
                f'Annotated[Union[{union}], Field(discriminator="type")]'
            )
            uses_annotated = True
        pattern = re.compile(
            rf"^(    {field_name}: )list\[Union\[[^\n]+\]\]( = Field\()",
            re.MULTILINE,
        )
        models, replacements = pattern.subn(
            rf"\g<1>list[{value_annotation}]\g<2>", models
        )
        if replacements != 1:
            raise ValueError(
                f"Expected one generated Scene.{field_name} union, "
                f"found {replacements}"
            )

    if uses_annotated:
        models, replacements = re.subn(
            r"(from typing import \(\n)",
            r"\1    Annotated,\n",
            models,
            count=1,
        )
        if replacements != 1:
            raise ValueError("Generated models have no typing import block")
    return models


def _concrete_descendants(view: SchemaView, parent: str) -> tuple[str, ...]:
    names = view.class_descendants(parent, reflexive=False)
    return tuple(
        sorted(
            str(name)
            for name in names
            if _required_class(view, str(name)).abstract is not True
        )
    )


def _required_class(view: SchemaView, name: str) -> Any:
    definition = view.get_class(name)
    if definition is None:
        raise ValueError(f"Unknown LinkML class: {name}")
    return definition


def _annotation(element: Any, name: str) -> str | None:
    annotations = element.annotations
    if name not in annotations:
        return None
    annotation = annotations[name]
    value = annotation.value
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"LinkML annotation {name} must be a nonempty string")
    return value.strip()


def _description(definition: Any, name: str) -> str:
    description = definition.description
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"LinkML class {name} needs a description")
    return description.strip()


def _snake_case(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def _write(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    print(f"[schema] wrote: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    raise SystemExit(main())
