from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from linkml.generators.pydanticgen import PydanticGenerator
from linkml.generators.pydanticgen.pydanticgen import MetadataMode
from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "scene_graph.yaml"
GENERATED_DIRECTORY = ROOT / "src" / "graph" / "_generated"
MODELS_PATH = GENERATED_DIRECTORY / "models.py"
CATALOG_PATH = GENERATED_DIRECTORY / "catalog.py"
GENERATED_HEADER = (
    "# Generated by scripts/compile_schema.py from schema/scene_graph.yaml.\n"
    "# Do not edit this file directly.\n\n"
)


def main() -> int:
    print(f"[schema] compile started: {SCHEMA_PATH.relative_to(ROOT)}")
    view = SchemaView(str(SCHEMA_PATH))
    models = PydanticGenerator(
        SCHEMA_PATH,
        metadata_mode=MetadataMode.NONE,
        extra_fields="forbid",
    ).serialize()
    models = _restrict_scene_collections(models, view)
    catalog = _catalog_source(view)

    GENERATED_DIRECTORY.mkdir(parents=True, exist_ok=True)
    _write(MODELS_PATH, GENERATED_HEADER + models)
    _write(CATALOG_PATH, GENERATED_HEADER + catalog)
    print("[schema] compile finished")
    return 0


def _catalog_source(view: SchemaView) -> str:
    detection_targets = []
    for name in _concrete_descendants(view, "PerceivedRoadUser"):
        prompt = _annotation(view.get_class(name), "object_detection_prompt")
        if prompt is not None:
            detection_targets.append((name, prompt))
    prompts: dict[str, str] = {}
    for name, prompt in detection_targets:
        previous = prompts.get(prompt.casefold())
        if previous is not None:
            raise ValueError(
                f"Detection prompt {prompt!r} belongs to both {previous} and {name}"
            )
        prompts[prompt.casefold()] = name

    relationship_targets = []
    relationship_by_object_range: dict[str, list[str]] = {}
    for name in _concrete_descendants(view, "Relationship"):
        definition = _required_class(view, name)
        subject_range = str(view.induced_slot("subject", name).range)
        object_range = str(view.induced_slot("object", name).range)
        exclusive_group = _annotation(definition, "exclusive_group")
        extraction_enabled = (
            _annotation(definition, "relation_extraction") == "enabled"
        )
        relationship_targets.append(
            (
                name,
                _description(definition, name),
                subject_range,
                object_range,
                exclusive_group,
                extraction_enabled,
            )
        )
        if name in _concrete_descendants(view, "RoadRegionRelationship"):
            relationship_by_object_range.setdefault(object_range, []).append(name)

    road_region_targets = []
    for name in _concrete_descendants(view, "RoadRegion"):
        memberships = relationship_by_object_range.get(name, [])
        if len(memberships) != 1:
            raise ValueError(
                f"Road region {name} needs exactly one concrete membership "
                f"relationship, found {memberships}"
            )
        road_region_targets.append(
            (
                name,
                _description(_required_class(view, name), name),
                memberships[0],
                _snake_case(name),
            )
        )

    state_targets = []
    system_fields = {"type", "subject", "provenance"}
    for name in _concrete_descendants(view, "ObjectState"):
        definition = _required_class(view, name)
        subject_range = str(view.induced_slot("subject", name).range)
        attributes = []
        for slot in view.class_induced_slots(name):
            slot_name = str(slot.name)
            if slot_name in system_fields:
                continue
            if slot.multivalued:
                raise ValueError(f"Object state field {name}.{slot_name} cannot be multivalued")
            enum_definition = view.get_enum(slot.range)
            if enum_definition is None:
                raise ValueError(
                    f"Object state field {name}.{slot_name} must use an enum"
                )
            values = []
            for value, permissible in enum_definition.permissible_values.items():
                prompt = _annotation(permissible, "relation_extraction_prompt")
                if prompt is None:
                    raise ValueError(
                        f"State value {enum_definition.name}.{value} needs a "
                        "relation_extraction_prompt annotation"
                    )
                values.append(
                    (
                        str(value),
                        permissible.description or str(value),
                        prompt,
                    )
                )
            attributes.append(
                (
                    slot_name,
                    slot.description or enum_definition.description or slot_name,
                    values,
                )
            )
        if not attributes:
            raise ValueError(f"Object state {name} has no value fields")
        state_targets.append(
            (
                name,
                _description(definition, name),
                subject_range,
                attributes,
            )
        )

    concrete_road_users = _concrete_descendants(view, "PerceivedRoadUser")
    concrete_road_regions = _concrete_descendants(view, "RoadRegion")
    concrete_relationships = _concrete_descendants(view, "Relationship")
    concrete_states = _concrete_descendants(view, "ObjectState")
    model_names = {
        *(name for name, _ in detection_targets),
        *(item for target in road_region_targets for item in (target[0], target[2])),
        *(item for target in relationship_targets for item in (target[0], target[2], target[3])),
        *(item for target in state_targets for item in (target[0], target[2])),
        *concrete_road_users,
        *concrete_road_regions,
        *concrete_relationships,
        *concrete_states,
    }

    lines = [
        "from __future__ import annotations",
        "",
        "from src.graph._generated.models import (",
        *(f"    {name}," for name in sorted(model_names)),
        ")",
        "from src.graph.ontology import (",
        "    DetectionTarget,",
        "    RelationshipTarget,",
        "    RoadRegionTarget,",
        "    StateAttribute,",
        "    StateTarget,",
        "    StateValue,",
        ")",
        "",
        "",
        "DETECTION_TARGETS = (",
    ]
    for name, prompt in sorted(detection_targets, key=lambda item: item[1].casefold()):
        lines.extend(
            [
                "    DetectionTarget(",
                f"        model={name},",
                f"        prompt={prompt!r},",
                "    ),",
            ]
        )
    lines.extend([")", "", "", "ROAD_REGION_TARGETS = ("])
    for name, description, membership, prefix in sorted(road_region_targets):
        lines.extend(
            [
                "    RoadRegionTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        membership_model={membership},",
                f"        id_prefix={prefix!r},",
                "    ),",
            ]
        )
    lines.extend([")", "", "", "RELATIONSHIP_TARGETS = ("])
    for (
        name,
        description,
        subject_range,
        object_range,
        exclusive_group,
        extraction_enabled,
    ) in sorted(relationship_targets):
        lines.extend(
            [
                "    RelationshipTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        subject_model={subject_range},",
                f"        object_model={object_range},",
                f"        exclusive_group={exclusive_group!r},",
                f"        extraction_enabled={extraction_enabled!r},",
                "    ),",
            ]
        )
    lines.extend([")", "", "", "STATE_TARGETS = ("])
    for name, description, subject_range, attributes in sorted(state_targets):
        lines.extend(
            [
                "    StateTarget(",
                f"        model={name},",
                f"        description={description!r},",
                f"        subject_model={subject_range},",
                "        attributes=(",
            ]
        )
        for attribute_name, attribute_description, values in attributes:
            lines.extend(
                [
                    "            StateAttribute(",
                    f"                name={attribute_name!r},",
                    f"                description={attribute_description!r},",
                    "                values=(",
                ]
            )
            for value, value_description, prompt in values:
                lines.extend(
                    [
                        "                    StateValue(",
                        f"                        value={value!r},",
                        f"                        description={value_description!r},",
                        f"                        prompt={prompt!r},",
                        "                    ),",
                    ]
                )
            lines.extend(["                ),", "            ),"])
        lines.extend(["        ),", "    ),"])
    lines.extend([")", ""])
    return "\n".join(lines)


def _restrict_scene_collections(models: str, view: SchemaView) -> str:
    collection_models = {
        "road_users": _concrete_descendants(view, "PerceivedRoadUser"),
        "road_regions": _concrete_descendants(view, "RoadRegion"),
        "states": _concrete_descendants(view, "ObjectState"),
        "relationships": _concrete_descendants(view, "Relationship"),
    }
    uses_annotated = False
    for field_name, model_names in collection_models.items():
        if not model_names:
            raise ValueError(f"Scene.{field_name} has no concrete model types")
        if len(model_names) == 1:
            value_annotation = model_names[0]
        else:
            union = ",".join(model_names)
            value_annotation = (
                f'Annotated[Union[{union}], Field(discriminator="type")]'
            )
            uses_annotated = True
        pattern = re.compile(
            rf"^(    {field_name}: Optional\[list\[)Union\[[^\n]+\](\]\] = Field\()",
            re.MULTILINE,
        )
        models, replacements = pattern.subn(
            rf"\g<1>{value_annotation}\g<2>", models
        )
        if replacements != 1:
            raise ValueError(
                f"Expected one generated Scene.{field_name} union, "
                f"found {replacements}"
            )

    if uses_annotated:
        models, replacements = re.subn(
            r"(from typing import \(\n)",
            r"\1    Annotated,\n",
            models,
            count=1,
        )
        if replacements != 1:
            raise ValueError("Generated models have no typing import block")
    return models


def _concrete_descendants(view: SchemaView, parent: str) -> tuple[str, ...]:
    names = view.class_descendants(parent, reflexive=False)
    return tuple(
        sorted(
            str(name)
            for name in names
            if _required_class(view, str(name)).abstract is not True
        )
    )


def _required_class(view: SchemaView, name: str) -> Any:
    definition = view.get_class(name)
    if definition is None:
        raise ValueError(f"Unknown LinkML class: {name}")
    return definition


def _annotation(element: Any, name: str) -> str | None:
    annotation = element.annotations.get(name)
    if annotation is None:
        return None
    value = annotation.value
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"LinkML annotation {name} must be a nonempty string")
    return value.strip()


def _description(definition: Any, name: str) -> str:
    description = definition.description
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"LinkML class {name} needs a description")
    return description.strip()


def _snake_case(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def _write(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    print(f"[schema] wrote: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    raise SystemExit(main())
